export const idahoRegions = [
  "Treasure Valley",
  "Southwest Idaho",
  "Magic Valley",
  "Southeast Idaho",
  "Eastern Idaho",
  "Central Idaho",
  "North Central Idaho",
  "North Idaho",
] as const;

export const usStates = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
] as const;

export const classifiedCategories = [
  { slug: "cars-trucks", name: "Cars & Trucks", group: "motors" },
  { slug: "motorcycles", name: "Motorcycles", group: "motors" },
  { slug: "rvs-campers", name: "RVs & Campers", group: "motors" },
  { slug: "powersports", name: "Powersports", group: "motors" },
  { slug: "auto-parts", name: "Auto Parts", group: "motors" },
  { slug: "trailers", name: "Trailers", group: "motors" },
  { slug: "furniture", name: "Furniture", group: "classifieds" },
  { slug: "electronics", name: "Electronics", group: "classifieds" },
  { slug: "tools-equipment", name: "Tools & Equipment", group: "classifieds" },
  { slug: "outdoor-sporting", name: "Outdoor & Sporting", group: "classifieds" },
  { slug: "farm-garden", name: "Farm & Garden", group: "classifieds" },
  { slug: "general", name: "General", group: "classifieds" },
  { slug: "other-real-estate", name: "Homes", group: "classifieds" },
  { slug: "services", name: "Services", group: "classifieds" },
  { slug: "jobs", name: "Jobs", group: "classifieds" },
] as const;

export const vehicleModelsByMake: Record<string, readonly string[]> = {
  Abarth: ["124 Spider", "500", "500e", "595", "695"],
  Acura: ["Integra", "ILX", "TL", "TLX", "RL", "RLX", "TSX", "MDX", "RDX", "ZDX", "NSX"],
  "Alfa Romeo": ["4C", "Giulia", "Stelvio", "Tonale"],
  "Aston Martin": [
    "DB7",
    "DB9",
    "DB11",
    "DB12",
    "DBS",
    "DBX",
    "Rapide",
    "V8 Vantage",
    "Vanquish",
    "Valkyrie",
  ],
  Audi: [
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "R8",
    "RS3",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "SQ7",
    "SQ8",
    "TT",
    "e-tron",
  ],
  Bentley: [
    "Arnage",
    "Azure",
    "Bentayga",
    "Continental",
    "Continental GT",
    "Flying Spur",
    "Mulsanne",
  ],
  BMW: [
    "1 Series",
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "6 Series",
    "7 Series",
    "8 Series",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "iX",
    "iX1",
    "iX3",
    "M2",
    "M3",
    "M4",
    "M5",
    "M8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "XM",
    "Z3",
    "Z4",
  ],
  Buick: [
    "Century",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "LaCrosse",
    "LeSabre",
    "Lucerne",
    "Regal",
    "Rendezvous",
    "Riviera",
    "Verano",
  ],
  Cadillac: [
    "ATS",
    "CT4",
    "CT5",
    "CTS",
    "DeVille",
    "DTS",
    "Eldorado",
    "Escalade",
    "LYRIQ",
    "SRX",
    "STS",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
  ],
  Chevrolet: [
    "Avalanche",
    "Blazer",
    "Bolt EV",
    "Bolt EUV",
    "Camaro",
    "Caprice",
    "Cavalier",
    "Colorado",
    "Corvette",
    "Cruze",
    "Equinox",
    "Express",
    "Impala",
    "Malibu",
    "Monte Carlo",
    "Prizm",
    "Silverado 1500",
    "Silverado 2500",
    "Silverado 3500",
    "Sonic",
    "Spark",
    "Suburban",
    "Tahoe",
    "Trailblazer",
    "Traverse",
    "Trax",
    "Volt",
  ],
  Chrysler: [
    "200",
    "300",
    "Aspen",
    "Cirrus",
    "Concorde",
    "Crossfire",
    "Pacifica",
    "PT Cruiser",
    "Sebring",
    "Town & Country",
    "Voyager",
  ],
  Daewoo: ["Lanos", "Leganza", "Nubira"],
  Daihatsu: ["Charade", "Rocky", "Terios"],
  Dodge: [
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger",
    "Charger",
    "Dart",
    "Durango",
    "Grand Caravan",
    "Hornet",
    "Journey",
    "Magnum",
    "Neon",
    "Nitro",
    "Ram 1500",
    "Sprinter",
    "Viper",
  ],
  Ducati: [
    "Diavel",
    "Hypermotard",
    "Monster",
    "Multistrada",
    "Panigale",
    "Scrambler",
    "SuperSport",
  ],
  Eagle: ["Talon", "Vision", "Summit", "Premier"],
  Fiat: ["124 Spider", "500", "500e", "500L", "500X", "500 Abarth"],
  Fisker: ["Karma", "Ocean", "Pearl", "Ronin"],
  Ford: [
    "Bronco",
    "Bronco Sport",
    "C-Max",
    "Crown Victoria",
    "EcoSport",
    "Edge",
    "Escape",
    "Expedition",
    "Explorer",
    "F-150",
    "F-150 Lightning",
    "F-250",
    "F-350",
    "F-450",
    "F-550",
    "Fairmont",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Freestar",
    "Fusion",
    "Galaxie",
    "GT",
    "Maverick",
    "Mustang",
    "Mustang Mach-E",
    "Ranger",
    "Taurus",
    "Thunderbird",
    "Transit",
    "Transit Connect",
    "Windstar",
  ],
  Freightliner: ["Cascadia", "Columbia", "Coronado", "M2", "Sprinter", "114SD", "122SD"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "GV90"],
  Geo: ["Metro", "Prizm", "Storm", "Tracker"],
  GMC: [
    "Acadia",
    "Canyon",
    "Envoy",
    "Hummer EV",
    "Jimmy",
    "Safari",
    "Savana",
    "Sierra 1500",
    "Sierra 2500",
    "Sierra 3500",
    "Sonoma",
    "Terrain",
    "Typhoon",
    "Yukon",
    "Yukon XL",
  ],
  "Harley-Davidson": [
    "CVO",
    "Electra Glide",
    "Fat Boy",
    "Iron 883",
    "LiveWire",
    "Low Rider",
    "Pan America",
    "Road Glide",
    "Road King",
    "Softail",
    "Sportster",
    "Street Glide",
    "Tri Glide",
    "Ultra Limited",
  ],
  Hino: ["195", "258", "268", "338", "L Series", "XL Series"],
  Honda: [
    "Accord",
    "Civic",
    "Clarity",
    "CR-V",
    "CR-Z",
    "Crosstour",
    "Element",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Ridgeline",
    "S2000",
    "CBR600RR",
    "CBR1000RR",
    "CRF250R",
    "CRF450R",
    "CRF300L",
    "Gold Wing",
    "Grom",
    "Monkey",
    "Rebel 300",
    "Rebel 500",
    "Shadow",
    "Africa Twin",
    "FourTrax",
    "Pioneer",
    "Talon",
  ],
  Hummer: ["H1", "H2", "H3", "EV Pickup", "EV SUV"],
  Hyundai: [
    "Accent",
    "Azera",
    "Elantra",
    "Equus",
    "Genesis Coupe",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Kona",
    "Nexo",
    "Palisade",
    "Santa Cruz",
    "Santa Fe",
    "Sonata",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Venue",
  ],
  Indian: ["Challenger", "Chieftain", "FTR", "Pursuit", "Roadmaster", "Scout", "Springfield"],
  Infiniti: [
    "EX35",
    "FX35",
    "G20",
    "G35",
    "G37",
    "I30",
    "JX35",
    "M35",
    "Q40",
    "Q50",
    "Q60",
    "Q70",
    "QX4",
    "QX30",
    "QX50",
    "QX55",
    "QX56",
    "QX60",
    "QX80",
  ],
  International: ["CV", "Durastar", "LT", "LoneStar", "MV", "ProStar", "TerraStar", "WorkStar"],
  Isuzu: [
    "Amigo",
    "Ascender",
    "Axiom",
    "Hombre",
    "i-280",
    "i-290",
    "i-370",
    "NPR",
    "NQR",
    "NRR",
    "Rodeo",
    "Trooper",
  ],
  Jaguar: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "X-Type", "XE", "XF", "XJ", "XK"],
  Jeep: [
    "Cherokee",
    "Comanche",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Cherokee L",
    "Liberty",
    "Patriot",
    "Renegade",
    "Wagoneer",
    "Wrangler",
  ],
  Kawasaki: [
    "Concours",
    "KLR650",
    "KX250",
    "KX450",
    "Ninja 400",
    "Ninja 650",
    "Ninja ZX-6R",
    "Ninja ZX-10R",
    "Vulcan",
    "Versys",
    "Z900",
    "Z125",
    "Mule",
    "Ninja H2",
  ],
  Karma: ["GS-6", "Revero"],
  Kenworth: ["K270", "K370", "T170", "T270", "T370", "T680", "T880", "W900"],
  Kia: [
    "Cadenza",
    "Carnival",
    "EV6",
    "EV9",
    "Forte",
    "K4",
    "K5",
    "K900",
    "Niro",
    "Optima",
    "Rio",
    "Sedona",
    "Seltos",
    "Soul",
    "Sorento",
    "Soul EV",
    "Sportage",
    "Stinger",
    "Telluride",
  ],
  KTM: [
    "1290 Super Duke",
    "1290 Super Adventure",
    "390 Adventure",
    "390 Duke",
    "500 EXC-F",
    "690 Enduro",
    "790 Adventure",
    "890 Adventure",
    "RC 390",
    "SX-F",
  ],
  Lamborghini: ["Aventador", "Countach", "Gallardo", "Huracan", "Revuelto", "Urus"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: [
    "CT",
    "ES",
    "GS",
    "GX",
    "IS",
    "LC",
    "LFA",
    "LS",
    "LX",
    "NX",
    "RC",
    "RX",
    "RZ",
    "SC",
    "TX",
    "UX",
  ],
  Lincoln: [
    "Aviator",
    "Continental",
    "Corsair",
    "LS",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Town Car",
  ],
  Lotus: ["Elise", "Emira", "Eletre", "Evora", "Exige"],
  Lucid: ["Air", "Gravity"],
  Mack: ["Anthem", "Granite", "LR", "Pinnacle", "TerraPro"],
  Maserati: ["Ghibli", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  Maybach: ["GLS", "S-Class", "S 580", "S 680"],
  Mazda: [
    "2",
    "3",
    "5",
    "6",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-7",
    "CX-9",
    "CX-90",
    "Miata",
    "Millenia",
    "MPV",
    "MX-5 Miata",
    "RX-7",
    "RX-8",
    "Tribute",
  ],
  McLaren: ["570S", "600LT", "650S", "720S", "750S", "765LT", "Artura", "GT", "P1", "Senna"],
  "Mercedes-Benz": [
    "A-Class",
    "B-Class",
    "C-Class",
    "CLA",
    "CLK",
    "CLS",
    "E-Class",
    "EQS",
    "EQE",
    "G-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLK",
    "GLS",
    "M-Class",
    "Metris",
    "R-Class",
    "S-Class",
    "SL",
    "SLC",
    "SLK",
    "Sprinter",
    "AMG GT",
    "EQA",
    "EQB",
    "EQC",
    "EQV",
  ],
  Mercury: [
    "Cougar",
    "Grand Marquis",
    "Marauder",
    "Mariner",
    "Milan",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Sable",
    "Tracer",
    "Villager",
  ],
  MINI: ["Clubman", "Cooper", "Countryman", "Hardtop", "Paceman", "Convertible", "SE"],
  Mitsubishi: [
    "3000GT",
    "Eclipse",
    "Eclipse Cross",
    "Endeavor",
    "Galant",
    "Lancer",
    "Mirage",
    "Montero",
    "Outlander",
    "Outlander Sport",
    "Raider",
  ],
  "Moto Guzzi": ["California", "Griso", "MGX-21", "V7", "V85 TT"],
  Nissan: [
    "200SX",
    "240SX",
    "300ZX",
    "350Z",
    "370Z",
    "Altima",
    "Armada",
    "Cube",
    "Frontier",
    "GT-R",
    "Juke",
    "Kicks",
    "Leaf",
    "Maxima",
    "Murano",
    "NV",
    "NV200",
    "Pathfinder",
    "Quest",
    "Rogue",
    "Sentra",
    "Titan",
    "Versa",
    "Xterra",
    "Ariya",
  ],
  Oldsmobile: ["Alero", "Aurora", "Bravada", "Cutlass", "Intrigue", "Silhouette"],
  Peterbilt: ["337", "348", "389", "567", "579", "589"],
  Polaris: [
    "General",
    "Ranger",
    "RZR",
    "Scrambler",
    "Slingshot",
    "Sportsman",
    "Trailblazer",
    "Voyager",
    "Xpedition",
  ],
  Polestar: ["1", "2", "3", "4"],
  Pontiac: [
    "Aztek",
    "Bonneville",
    "Firebird",
    "G5",
    "G6",
    "Grand Prix",
    "GTO",
    "Montana",
    "Solstice",
    "Sunfire",
    "Torrent",
    "Vibe",
  ],
  Porsche: [
    "718 Boxster",
    "718 Cayman",
    "911",
    "944",
    "968",
    "Carrera GT",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  Ram: ["1500", "1500 Classic", "2500", "3500", "4500", "5500", "ProMaster", "ProMaster City"],
  Rivian: ["R1S", "R1T", "R2", "R3", "R3X", "EDV"],
  "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Spectre", "Wraith"],
  "Royal Enfield": [
    "Bullet",
    "Classic 350",
    "Continental GT",
    "Himalayan",
    "Hunter 350",
    "Interceptor",
    "Meteor",
    "Shotgun",
  ],
  Saab: ["9-2X", "9-3", "9-4X", "9-5", "9-7X", "900", "9000"],
  Saturn: ["Aura", "Ion", "L-Series", "Outlook", "Relay", "Sky", "Vue"],
  Scion: ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
  Scout: ["Traveler", "Terra", "Rally", "Harvester"],
  Smart: ["EQ fortwo", "fortwo", "forfour"],
  Subaru: [
    "Ascent",
    "Baja",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Legacy",
    "Outback",
    "Solterra",
    "Tribeca",
    "WRX",
  ],
  Suzuki: [
    "Boulevard",
    "DR-Z400",
    "GSX-R600",
    "GSX-R750",
    "GSX-R1000",
    "Hayabusa",
    "Katana",
    "KingQuad",
    "SV650",
    "V-Strom",
    "Vitara",
    "Samurai",
    "Sidekick",
  ],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  "Thomas Built": ["Saf-T-Liner", "C2", "MVP-EF", "Jouley"],
  Toyota: [
    "4Runner",
    "86",
    "Avalon",
    "bZ4X",
    "Camry",
    "Celica",
    "C-HR",
    "Corolla",
    "Crown",
    "FJ Cruiser",
    "GR86",
    "GR Corolla",
    "GR Supra",
    "Highlander",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Tacoma",
    "Tercel",
    "Tundra",
    "Venza",
    "Yaris",
  ],
  Triumph: [
    "Bonneville",
    "Daytona",
    "Rocket 3",
    "Scrambler",
    "Speed Triple",
    "Street Triple",
    "Tiger",
    "Trident",
  ],
  VinFast: ["VF 6", "VF 7", "VF 8", "VF 9"],
  Volkswagen: [
    "Arteon",
    "Atlas",
    "Beetle",
    "CC",
    "Eos",
    "Golf",
    "GTI",
    "ID.4",
    "ID.7",
    "Jetta",
    "Passat",
    "Routan",
    "Taos",
    "Tiguan",
    "Touareg",
    "Transporter",
    "Vanagon",
  ],
  Volvo: [
    "C30",
    "C40",
    "S40",
    "S60",
    "S80",
    "S90",
    "V40",
    "V50",
    "V60",
    "V70",
    "V90",
    "XC40",
    "XC60",
    "XC70",
    "XC90",
    "EX30",
    "EX90",
  ],
  "Western Star": ["4700", "4800", "4900", "5700", "6900"],
  Winnebago: ["Brave", "Forza", "Minnie Winnie", "Reyo", "Revel", "Solitude", "View", "Vista"],
  Yamaha: [
    "Bolt",
    "FJR1300",
    "MT-03",
    "MT-07",
    "MT-09",
    "R1",
    "R3",
    "R6",
    "Tenere 700",
    "V Star",
    "WR250R",
    "YZ250F",
    "YZ450F",
    "Grizzly",
    "Raptor",
    "Viking",
    "Wolverine",
  ],
  Zero: ["DS", "FX", "FXS", "S", "SR", "SR/F", "SR/S"],
  Airstream: [
    "Basecamp",
    "Classic",
    "Flying Cloud",
    "International",
    "Interstate",
    "Pottery Barn",
    "Rangeline",
  ],
  Coachmen: ["Apex", "Catalina", "Freedom Express", "Leprechaun", "Mirada", "Prism", "Sportscoach"],
  Dutchmen: ["Aerolite", "Aspen Trail", "Coleman", "Kodiak", "Tiburon", "Voltage"],
  Entegra: ["Accolade", "Anthem", "Aspire", "Cornerstone", "Emblem", "Odyssey", "Reatta"],
  Fleetwood: ["Bounder", "Discovery", "Fortis", "Pace Arrow", "Southwind"],
  "Forest River": [
    "Cardinal",
    "Cedar Creek",
    "Cherokee",
    "Coachmen",
    "Flagstaff",
    "Grey Wolf",
    "Rockwood",
    "Salem",
    "Sunseeker",
    "Wildcat",
  ],
  "Grand Design": ["Imagine", "Momentum", "Reflection", "Solitude", "Transcend"],
  Heartland: ["Big Country", "Bighorn", "Cyclone", "Landmark", "North Trail", "Prowler"],
  Jayco: ["Alante", "Eagle", "Greyhawk", "Jay Flight", "Melbourne", "Redhawk", "White Hawk"],
  Keystone: ["Cougar", "Fuzion", "Montana", "Passport", "Raptor", "Springdale"],
  KZ: ["Connect", "Durango", "Sportsmen", "Sportsmen Classic", "Venom"],
  Lance: ["1172", "2285", "2375", "2465", "850", "975"],
  Newmar: ["Dutch Star", "Kountry Star", "Mountain Aire", "New Aire", "Ventana"],
  Nexus: ["Bentley", "Ghost", "Maybach", "Phantom", "Rebel", "Viper"],
  "Pleasure-Way": ["Ascent", "Ontour", "Recon", "Trek"],
  Thor: ["A.C.E.", "Axis", "Four Winds", "Gemini", "Hurricane", "Quantum", "Tranquility"],
  Tiffin: ["Allegro", "Phaeton", "Red", "Wayfarer"],
  "Travel Lite": ["Falcon", "Fantom", "Rove", "Trek"],
  Vanleigh: ["Beacon", "Brazos", "Vilano"],
  "Big Tex": ["14LP", "14PI", "14TL", "14OA", "Gooseneck"],
  "Carry-On": ["5x8", "6x12", "7x14", "Utility", "Landscape"],
  "Cargo Mate": ["Blazer", "Eliminator", "E-Series", "Nitro"],
  Featherlite: ["8127", "8581", "9409", "9701"],
  Haulmark: ["Edge", "Passport", "Transport", "Trailer"],
  "Load Trail": ["Dump", "Equipment", "Gooseneck", "Utility"],
  "PJ Trailers": ["Dump", "Equipment", "Flatdeck", "Gooseneck", "Utility"],
  "Sure-Trac": ["Dump", "Equipment", "Funnel", "Utility"],
  "Wells Cargo": ["Road Force", "Roadside", "RF", "Trailer"],
};

export const vehicleOptions = {
  makes: Object.keys(vehicleModelsByMake).sort((a, b) => a.localeCompare(b)),
  bodyStyles: ["Sedan", "SUV", "Pickup", "Coupe", "Hatchback", "Wagon", "Van", "Convertible"],
  transmissions: ["Automatic", "Manual", "CVT"],
  drivetrains: ["FWD", "RWD", "AWD", "4WD"],
  fuelTypes: ["Gasoline", "Diesel", "Hybrid", "Plug-in hybrid", "Electric", "Other"],
  exteriorColors: [
    "Black",
    "White",
    "Gray",
    "Silver",
    "Red",
    "Blue",
    "Green",
    "Brown",
    "Gold",
    "Orange",
    "Yellow",
    "Purple",
    "Other",
  ],
  titleStatuses: ["Clean", "Rebuilt", "Salvage", "Lien", "Other"],
} as const;

export type ClassifiedCategorySlug = (typeof classifiedCategories)[number]["slug"];
export type IdahoRegion = (typeof idahoRegions)[number];
