export const idahoRegions = [
  "Treasure Valley",
  "Southwest Idaho",
  "Magic Valley",
  "Southeast Idaho",
  "Eastern Idaho",
  "Central Idaho",
  "North Central Idaho",
  "North Idaho",
] as const;

export const usStates = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
] as const;

export const classifiedCategories = [
  { slug: "cars-trucks", name: "Cars & Trucks", group: "motors" },
  { slug: "motorcycles", name: "Motorcycles", group: "motors" },
  { slug: "rvs-campers", name: "RVs & Campers", group: "motors" },
  { slug: "powersports", name: "Powersports", group: "motors" },
  { slug: "auto-parts", name: "Auto Parts", group: "motors" },
  { slug: "trailers", name: "Trailers", group: "motors" },
  { slug: "furniture", name: "Furniture", group: "classifieds" },
  { slug: "electronics", name: "Electronics", group: "classifieds" },
  { slug: "tools-equipment", name: "Tools & Equipment", group: "classifieds" },
  { slug: "outdoor-sporting", name: "Outdoor & Sporting", group: "classifieds" },
  { slug: "farm-garden", name: "Farm & Garden", group: "classifieds" },
  { slug: "general", name: "General", group: "classifieds" },
] as const;

export const vehicleOptions = {
  makes: [
    "Acura",
    "Audi",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ford",
    "Genesis",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jeep",
    "Kia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Mazda",
    "Mercedes-Benz",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
  ],
  bodyStyles: ["Sedan", "SUV", "Pickup", "Coupe", "Hatchback", "Wagon", "Van", "Convertible"],
  transmissions: ["Automatic", "Manual", "CVT"],
  drivetrains: ["FWD", "RWD", "AWD", "4WD"],
  fuelTypes: ["Gasoline", "Diesel", "Hybrid", "Plug-in hybrid", "Electric", "Other"],
  exteriorColors: [
    "Black",
    "White",
    "Gray",
    "Silver",
    "Red",
    "Blue",
    "Green",
    "Brown",
    "Gold",
    "Orange",
    "Yellow",
    "Purple",
    "Other",
  ],
  titleStatuses: ["Clean", "Rebuilt", "Salvage", "Lien", "Other"],
} as const;

export type ClassifiedCategorySlug = (typeof classifiedCategories)[number]["slug"];
export type IdahoRegion = (typeof idahoRegions)[number];
