export const petSubcategories = [
  ["birds", "Birds"],
  ["cats", "Cats"],
  ["dogs", "Dogs"],
  ["dogs-studs-breeding", "Dogs — Studs/Breeding"],
  ["ferrets", "Ferrets"],
  ["fish", "Fish"],
  ["guinea-pigs", "Guinea Pigs"],
  ["hamsters", "Hamsters"],
  ["hedgehogs", "Hedgehogs"],
  ["horses", "Horses"],
  ["lost-found", "Lost and Found Pets"],
  ["livestock", "Livestock"],
  ["other-pets", "Other Pets"],
  ["pet-equipment-supplies", "Pet Equipment and Supplies"],
  ["poultry", "Poultry"],
  ["rabbits", "Rabbits"],
  ["reptiles", "Reptiles"],
  ["small-animals", "Small Animals"],
  ["stock-dogs", "Stock Dogs"],
  ["wanted-iso", "Wanted/ISO — Pets"],
] as const;

export const petSpecies = [
  "Dog",
  "Cat",
  "Bird",
  "Fish",
  "Ferret",
  "Guinea Pig",
  "Hamster",
  "Hedgehog",
  "Horse",
  "Livestock",
  "Poultry",
  "Rabbit",
  "Reptile",
  "Amphibian",
  "Small animal",
  "Other",
] as const;

export const petBreedsBySpecies: Record<string, readonly string[]> = {
  Dog: [
    "Affenpinscher",
    "Akita",
    "Alaskan Malamute",
    "American Eskimo Dog",
    "American Staffordshire Terrier",
    "Anatolian Shepherd",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Australian Terrier",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Belgian Malinois",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Bloodhound",
    "Bluetick Coonhound",
    "Border Collie",
    "Borzoi",
    "Boston Terrier",
    "Boxer",
    "Brittany",
    "Brussels Griffon",
    "Bulldog",
    "Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chinese Crested",
    "Chow Chow",
    "Cocker Spaniel",
    "Collie",
    "Coton de Tulear",
    "Curly-Coated Retriever",
    "Dachshund",
    "Dalmatian",
    "Doberman Pinscher",
    "English Cocker Spaniel",
    "English Setter",
    "English Springer Spaniel",
    "French Bulldog",
    "German Shepherd",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Golden Retriever",
    "Goldendoodle",
    "Havanese",
    "Husky",
    "Irish Setter",
    "Irish Wolfhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Keeshond",
    "Komondor",
    "Kuvasz",
    "Lagotto Romagnolo",
    "Labrador Retriever",
    "Labradoodle",
    "Leonberger",
    "Lhasa Apso",
    "Maltese",
    "Mastiff",
    "Miniature American Shepherd",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Old English Sheepdog",
    "Papillon",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Pit Bull type",
    "Pointer",
    "Pomeranian",
    "Poodle",
    "Portuguese Water Dog",
    "Pug",
    "Rat Terrier",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Shetland Sheepdog",
    "Soft Coated Wheaten Terrier",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Tibetan Mastiff",
    "Toy Fox Terrier",
    "Vizsla",
    "Weimaraner",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Wirehaired Pointing Griffon",
    "Yorkshire Terrier",
    "Mixed breed",
    "Other",
    "Unknown",
  ],
  Cat: [
    "Abyssinian",
    "American Bobtail",
    "American Shorthair",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Shorthair",
    "Burmese",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Domestic Longhair",
    "Domestic Medium Hair",
    "Domestic Shorthair",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Himalayan",
    "Japanese Bobtail",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Shorthair",
    "Persian",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Sphynx",
    "Tabby",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
    "Mixed breed",
    "Other",
    "Unknown",
  ],
  Bird: [
    "African Grey",
    "Amazon",
    "Budgerigar/Parakeet",
    "Canary",
    "Chicken",
    "Cockatiel",
    "Cockatoo",
    "Conure",
    "Dove",
    "Duck",
    "Eclectus",
    "Emu",
    "Finch",
    "Goose",
    "Macaw",
    "Lovebird",
    "Parrot",
    "Pigeon",
    "Quail",
    "Parrotlet",
    "Robin",
    "Swan",
    "Toucan",
    "Turkey",
    "Other",
    "Unknown",
  ],
  Fish: [
    "Angelfish",
    "Betta",
    "Cichlid",
    "Clownfish",
    "Discus",
    "Goldfish",
    "Gourami",
    "Guppy",
    "Koi",
    "Molly",
    "Oscar",
    "Plecostomus",
    "Rasbora",
    "Tetra",
    "Tiger Barb",
    "Zebra Danio",
    "Saltwater/Marine",
    "Other",
    "Unknown",
  ],
  "Small animal": [
    "Chinchilla",
    "Degu",
    "Ferret",
    "Gerbil",
    "Guinea Pig",
    "Hamster",
    "Hedgehog",
    "Mouse",
    "Rat",
    "Rabbit",
    "Other",
    "Unknown",
  ],
  Reptile: [
    "Boa",
    "Bearded Dragon",
    "Chameleon",
    "Corn Snake",
    "Crested Gecko",
    "Gecko",
    "Iguana",
    "Leopard Gecko",
    "Milk Snake",
    "Python",
    "Skink",
    "Tortoise",
    "Turtle",
    "Uromastyx",
    "Other",
    "Unknown",
  ],
  Amphibian: ["Newt", "Frog", "Axolotl", "Other", "Unknown"],
  Horse: [
    "Appaloosa",
    "Arabian",
    "Clydesdale",
    "Friesian",
    "Haflinger",
    "Morgan",
    "Mustang",
    "Paint",
    "Palomino",
    "Quarter Horse",
    "Tennessee Walker",
    "Thoroughbred",
    "Other",
    "Unknown",
  ],
  Livestock: [
    "Alpaca",
    "Beef cattle",
    "Dairy cattle",
    "Goat",
    "Llama",
    "Pig",
    "Sheep",
    "Other",
    "Unknown",
  ],
  Poultry: [
    "Chicken",
    "Duck",
    "Goose",
    "Guinea fowl",
    "Peacock",
    "Pheasant",
    "Quail",
    "Turkey",
    "Other",
    "Unknown",
  ],
  Other: ["Other", "Unknown"],
};

export const petPlacementTypes = [
  ["sale", "For sale"],
  ["adoption", "Adoption"],
  ["rehoming", "Rehoming"],
  ["free", "Free"],
  ["stud_breeding", "Stud / breeding"],
  ["lost_found", "Lost or found"],
  ["wanted", "Wanted / ISO"],
] as const;

export const petOfferedBy = [
  "Owner",
  "Breeder",
  "Rescue",
  "Shelter",
  "Foster",
  "Business",
] as const;
export const petSexes = ["Male", "Female", "Unknown / not disclosed"] as const;
export const petYesNoUnknown = ["Yes", "No", "Unknown"] as const;
export const petIndoorOutdoor = ["Indoor", "Outdoor", "Indoor / outdoor", "Unknown"] as const;

export function isPetSubcategory(category: string) {
  return category === "pets";
}

export function petSpeciesForSubcategory(subcategory: string) {
  if (["cats"].includes(subcategory)) return ["Cat"] as const;
  if (["dogs", "dogs-studs-breeding", "stock-dogs"].includes(subcategory)) return ["Dog"] as const;
  if (["fish"].includes(subcategory)) return ["Fish"] as const;
  if (["ferrets"].includes(subcategory)) return ["Ferret"] as const;
  if (["guinea-pigs"].includes(subcategory)) return ["Guinea Pig"] as const;
  if (["hamsters"].includes(subcategory)) return ["Hamster"] as const;
  if (["hedgehogs"].includes(subcategory)) return ["Hedgehog"] as const;
  if (["rabbits"].includes(subcategory)) return ["Rabbit"] as const;
  if (["reptiles"].includes(subcategory)) return ["Reptile", "Amphibian"] as const;
  if (["birds"].includes(subcategory)) return ["Bird"] as const;
  if (["horses"].includes(subcategory)) return ["Horse"] as const;
  if (["livestock"].includes(subcategory)) return ["Livestock"] as const;
  if (["poultry"].includes(subcategory)) return ["Poultry"] as const;
  if (["small-animals"].includes(subcategory)) return ["Small animal"] as const;
  return petSpecies;
}

export function petSubcategoryForSelection(species: string, placementType = "sale") {
  if (placementType === "wanted") return "wanted-iso";
  if (placementType === "lost_found") return "lost-found";
  if (placementType === "stud_breeding" && species === "Dog") return "dogs-studs-breeding";
  const subcategoryBySpecies: Record<string, string> = {
    Dog: "dogs",
    Cat: "cats",
    Bird: "birds",
    Fish: "fish",
    Ferret: "ferrets",
    "Guinea Pig": "guinea-pigs",
    Hamster: "hamsters",
    Hedgehog: "hedgehogs",
    Horse: "horses",
    Livestock: "livestock",
    Poultry: "poultry",
    Rabbit: "rabbits",
    Reptile: "reptiles",
    Amphibian: "reptiles",
    "Small animal": "small-animals",
  };
  return subcategoryBySpecies[species] ?? "other-pets";
}
