/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBuyingRouteImport } from './routes/_authenticated/buying'
import { Route as AuthenticatedCreateListingRouteImport } from './routes/_authenticated/create-listing'
import { Route as AuthenticatedCreateMissingListingRouteImport } from './routes/_authenticated/create-missing-listing'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSellerSetupRouteImport } from './routes/_authenticated/seller-setup'
import { Route as AuthenticatedSellingRouteImport } from './routes/_authenticated/selling'
import { Route as AuthenticatedShopperRouteImport } from './routes/_authenticated/shopper'
import { Route as AuthenticatedShopperPayoutsRouteImport } from './routes/_authenticated/shopper-payouts'
import { Route as AuthenticatedSuggestRouteImport } from './routes/_authenticated/suggest'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as SellersSlugRouteImport } from './routes/sellers.$slug'
import { Route as ShoppersSlugRouteImport } from './routes/shoppers.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminClassifiedsRouteImport } from './routes/_authenticated/admin.classifieds'
import { Route as AuthenticatedAdminDealerInventoryRouteImport } from './routes/_authenticated/admin.dealer-inventory'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminValidationRouteImport } from './routes/_authenticated/admin.validation'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as ApiInternalReviewEmailsRouteImport } from './routes/api/internal/review-emails'
import { Route as ApiInternalSavedSearchesRouteImport } from './routes/api/internal/saved-searches'
import { Route as AuthenticatedAdminOrdersOrderIdRouteImport } from './routes/_authenticated/admin.orders.$orderId'
import { Route as AuthenticatedListingsListingIdEditRouteImport } from './routes/_authenticated/listings.$listingId.edit'
import { Route as ApiPublicCatalogMediaSplatRouteImport } from './routes/api/public/catalog-media.$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyingRoute = AuthenticatedBuyingRouteImport.update({
  id: '/buying',
  path: '/buying',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateListingRoute =
  AuthenticatedCreateListingRouteImport.update({
    id: '/create-listing',
    path: '/create-listing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreateMissingListingRoute =
  AuthenticatedCreateMissingListingRouteImport.update({
    id: '/create-missing-listing',
    path: '/create-missing-listing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerSetupRoute =
  AuthenticatedSellerSetupRouteImport.update({
    id: '/seller-setup',
    path: '/seller-setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellingRoute = AuthenticatedSellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopperRoute = AuthenticatedShopperRouteImport.update({
  id: '/shopper',
  path: '/shopper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopperPayoutsRoute =
  AuthenticatedShopperPayoutsRouteImport.update({
    id: '/shopper-payouts',
    path: '/shopper-payouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuggestRoute = AuthenticatedSuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSlugRoute = SellersSlugRouteImport.update({
  id: '/sellers/$slug',
  path: '/sellers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppersSlugRoute = ShoppersSlugRouteImport.update({
  id: '/shoppers/$slug',
  path: '/shoppers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassifiedsRoute =
  AuthenticatedAdminClassifiedsRouteImport.update({
    id: '/classifieds',
    path: '/classifieds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealerInventoryRoute =
  AuthenticatedAdminDealerInventoryRouteImport.update({
    id: '/dealer-inventory',
    path: '/dealer-inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminValidationRoute =
  AuthenticatedAdminValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiInternalReviewEmailsRoute = ApiInternalReviewEmailsRouteImport.update({
  id: '/api/internal/review-emails',
  path: '/api/internal/review-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalSavedSearchesRoute =
  ApiInternalSavedSearchesRouteImport.update({
    id: '/api/internal/saved-searches',
    path: '/api/internal/saved-searches',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOrdersOrderIdRoute =
  AuthenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedListingsListingIdEditRoute =
  AuthenticatedListingsListingIdEditRouteImport.update({
    id: '/listings/$listingId/edit',
    path: '/listings/$listingId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCatalogMediaSplatRoute =
  ApiPublicCatalogMediaSplatRouteImport.update({
    id: '/api/public/catalog-media/$',
    path: '/api/public/catalog-media/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/glossary': typeof GlossaryRoute
  '/policies': typeof PoliciesRoute
  '/sell': typeof SellRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/buying': typeof AuthenticatedBuyingRoute
  '/create-listing': typeof AuthenticatedCreateListingRoute
  '/create-missing-listing': typeof AuthenticatedCreateMissingListingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/seller-setup': typeof AuthenticatedSellerSetupRoute
  '/selling': typeof AuthenticatedSellingRoute
  '/shopper': typeof AuthenticatedShopperRoute
  '/shopper-payouts': typeof AuthenticatedShopperPayoutsRoute
  '/suggest': typeof AuthenticatedSuggestRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/shoppers/$slug': typeof ShoppersSlugRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/admin/dealer-inventory': typeof AuthenticatedAdminDealerInventoryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/internal/review-emails': typeof ApiInternalReviewEmailsRoute
  '/api/internal/saved-searches': typeof ApiInternalSavedSearchesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
  '/api/public/catalog-media/$': typeof ApiPublicCatalogMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/glossary': typeof GlossaryRoute
  '/policies': typeof PoliciesRoute
  '/sell': typeof SellRoute
  '/account': typeof AuthenticatedAccountRoute
  '/buying': typeof AuthenticatedBuyingRoute
  '/create-listing': typeof AuthenticatedCreateListingRoute
  '/create-missing-listing': typeof AuthenticatedCreateMissingListingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/seller-setup': typeof AuthenticatedSellerSetupRoute
  '/selling': typeof AuthenticatedSellingRoute
  '/shopper': typeof AuthenticatedShopperRoute
  '/shopper-payouts': typeof AuthenticatedShopperPayoutsRoute
  '/suggest': typeof AuthenticatedSuggestRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/shoppers/$slug': typeof ShoppersSlugRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/admin/dealer-inventory': typeof AuthenticatedAdminDealerInventoryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/internal/review-emails': typeof ApiInternalReviewEmailsRoute
  '/api/internal/saved-searches': typeof ApiInternalSavedSearchesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
  '/api/public/catalog-media/$': typeof ApiPublicCatalogMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/glossary': typeof GlossaryRoute
  '/policies': typeof PoliciesRoute
  '/sell': typeof SellRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/buying': typeof AuthenticatedBuyingRoute
  '/_authenticated/create-listing': typeof AuthenticatedCreateListingRoute
  '/_authenticated/create-missing-listing': typeof AuthenticatedCreateMissingListingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/seller-setup': typeof AuthenticatedSellerSetupRoute
  '/_authenticated/selling': typeof AuthenticatedSellingRoute
  '/_authenticated/shopper': typeof AuthenticatedShopperRoute
  '/_authenticated/shopper-payouts': typeof AuthenticatedShopperPayoutsRoute
  '/_authenticated/suggest': typeof AuthenticatedSuggestRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/shoppers/$slug': typeof ShoppersSlugRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/_authenticated/admin/dealer-inventory': typeof AuthenticatedAdminDealerInventoryRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/internal/review-emails': typeof ApiInternalReviewEmailsRoute
  '/api/internal/saved-searches': typeof ApiInternalSavedSearchesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/_authenticated/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
  '/api/public/catalog-media/$': typeof ApiPublicCatalogMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/glossary'
    | '/policies'
    | '/sell'
    | '/account'
    | '/admin'
    | '/buying'
    | '/create-listing'
    | '/create-missing-listing'
    | '/notifications'
    | '/onboarding'
    | '/seller-setup'
    | '/selling'
    | '/shopper'
    | '/shopper-payouts'
    | '/suggest'
    | '/watchlist'
    | '/listings/$listingId'
    | '/products/$slug'
    | '/sellers/$slug'
    | '/shoppers/$slug'
    | '/admin/catalog'
    | '/admin/classifieds'
    | '/admin/dealer-inventory'
    | '/admin/members'
    | '/admin/products'
    | '/admin/validation'
    | '/orders/$orderId'
    | '/api/internal/review-emails'
    | '/api/internal/saved-searches'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/listings/$listingId/edit'
    | '/api/public/catalog-media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/glossary'
    | '/policies'
    | '/sell'
    | '/account'
    | '/buying'
    | '/create-listing'
    | '/create-missing-listing'
    | '/notifications'
    | '/onboarding'
    | '/seller-setup'
    | '/selling'
    | '/shopper'
    | '/shopper-payouts'
    | '/suggest'
    | '/watchlist'
    | '/listings/$listingId'
    | '/products/$slug'
    | '/sellers/$slug'
    | '/shoppers/$slug'
    | '/admin/catalog'
    | '/admin/classifieds'
    | '/admin/dealer-inventory'
    | '/admin/members'
    | '/admin/products'
    | '/admin/validation'
    | '/orders/$orderId'
    | '/api/internal/review-emails'
    | '/api/internal/saved-searches'
    | '/admin'
    | '/admin/orders/$orderId'
    | '/listings/$listingId/edit'
    | '/api/public/catalog-media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/glossary'
    | '/policies'
    | '/sell'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/buying'
    | '/_authenticated/create-listing'
    | '/_authenticated/create-missing-listing'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/seller-setup'
    | '/_authenticated/selling'
    | '/_authenticated/shopper'
    | '/_authenticated/shopper-payouts'
    | '/_authenticated/suggest'
    | '/_authenticated/watchlist'
    | '/listings/$listingId'
    | '/products/$slug'
    | '/sellers/$slug'
    | '/shoppers/$slug'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/classifieds'
    | '/_authenticated/admin/dealer-inventory'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/validation'
    | '/_authenticated/orders/$orderId'
    | '/api/internal/review-emails'
    | '/api/internal/saved-searches'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/$orderId'
    | '/_authenticated/listings/$listingId/edit'
    | '/api/public/catalog-media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  GlossaryRoute: typeof GlossaryRoute
  PoliciesRoute: typeof PoliciesRoute
  SellRoute: typeof SellRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  SellersSlugRoute: typeof SellersSlugRoute
  ShoppersSlugRoute: typeof ShoppersSlugRoute
  ApiInternalReviewEmailsRoute: typeof ApiInternalReviewEmailsRoute
  ApiInternalSavedSearchesRoute: typeof ApiInternalSavedSearchesRoute
  ApiPublicCatalogMediaSplatRoute: typeof ApiPublicCatalogMediaSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buying': {
      id: '/_authenticated/buying'
      path: '/buying'
      fullPath: '/buying'
      preLoaderRoute: typeof AuthenticatedBuyingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-listing': {
      id: '/_authenticated/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof AuthenticatedCreateListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-missing-listing': {
      id: '/_authenticated/create-missing-listing'
      path: '/create-missing-listing'
      fullPath: '/create-missing-listing'
      preLoaderRoute: typeof AuthenticatedCreateMissingListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller-setup': {
      id: '/_authenticated/seller-setup'
      path: '/seller-setup'
      fullPath: '/seller-setup'
      preLoaderRoute: typeof AuthenticatedSellerSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selling': {
      id: '/_authenticated/selling'
      path: '/selling'
      fullPath: '/selling'
      preLoaderRoute: typeof AuthenticatedSellingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopper': {
      id: '/_authenticated/shopper'
      path: '/shopper'
      fullPath: '/shopper'
      preLoaderRoute: typeof AuthenticatedShopperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopper-payouts': {
      id: '/_authenticated/shopper-payouts'
      path: '/shopper-payouts'
      fullPath: '/shopper-payouts'
      preLoaderRoute: typeof AuthenticatedShopperPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suggest': {
      id: '/_authenticated/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof AuthenticatedSuggestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$slug': {
      id: '/sellers/$slug'
      path: '/sellers/$slug'
      fullPath: '/sellers/$slug'
      preLoaderRoute: typeof SellersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoppers/$slug': {
      id: '/shoppers/$slug'
      path: '/shoppers/$slug'
      fullPath: '/shoppers/$slug'
      preLoaderRoute: typeof ShoppersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classifieds': {
      id: '/_authenticated/admin/classifieds'
      path: '/classifieds'
      fullPath: '/admin/classifieds'
      preLoaderRoute: typeof AuthenticatedAdminClassifiedsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dealer-inventory': {
      id: '/_authenticated/admin/dealer-inventory'
      path: '/dealer-inventory'
      fullPath: '/admin/dealer-inventory'
      preLoaderRoute: typeof AuthenticatedAdminDealerInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/validation': {
      id: '/_authenticated/admin/validation'
      path: '/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AuthenticatedAdminValidationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/internal/review-emails': {
      id: '/api/internal/review-emails'
      path: '/api/internal/review-emails'
      fullPath: '/api/internal/review-emails'
      preLoaderRoute: typeof ApiInternalReviewEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/saved-searches': {
      id: '/api/internal/saved-searches'
      path: '/api/internal/saved-searches'
      fullPath: '/api/internal/saved-searches'
      preLoaderRoute: typeof ApiInternalSavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/orders/$orderId': {
      id: '/_authenticated/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/listings/$listingId/edit': {
      id: '/_authenticated/listings/$listingId/edit'
      path: '/listings/$listingId/edit'
      fullPath: '/listings/$listingId/edit'
      preLoaderRoute: typeof AuthenticatedListingsListingIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/catalog-media/$': {
      id: '/api/public/catalog-media/$'
      path: '/api/public/catalog-media/$'
      fullPath: '/api/public/catalog-media/$'
      preLoaderRoute: typeof ApiPublicCatalogMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminClassifiedsRoute: typeof AuthenticatedAdminClassifiedsRoute
  AuthenticatedAdminDealerInventoryRoute: typeof AuthenticatedAdminDealerInventoryRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminValidationRoute: typeof AuthenticatedAdminValidationRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdersOrderIdRoute: typeof AuthenticatedAdminOrdersOrderIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminClassifiedsRoute: AuthenticatedAdminClassifiedsRoute,
  AuthenticatedAdminDealerInventoryRoute:
    AuthenticatedAdminDealerInventoryRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminValidationRoute: AuthenticatedAdminValidationRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrdersOrderIdRoute: AuthenticatedAdminOrdersOrderIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBuyingRoute: typeof AuthenticatedBuyingRoute
  AuthenticatedCreateListingRoute: typeof AuthenticatedCreateListingRoute
  AuthenticatedCreateMissingListingRoute: typeof AuthenticatedCreateMissingListingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSellerSetupRoute: typeof AuthenticatedSellerSetupRoute
  AuthenticatedSellingRoute: typeof AuthenticatedSellingRoute
  AuthenticatedShopperRoute: typeof AuthenticatedShopperRoute
  AuthenticatedShopperPayoutsRoute: typeof AuthenticatedShopperPayoutsRoute
  AuthenticatedSuggestRoute: typeof AuthenticatedSuggestRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedListingsListingIdEditRoute: typeof AuthenticatedListingsListingIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBuyingRoute: AuthenticatedBuyingRoute,
  AuthenticatedCreateListingRoute: AuthenticatedCreateListingRoute,
  AuthenticatedCreateMissingListingRoute:
    AuthenticatedCreateMissingListingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSellerSetupRoute: AuthenticatedSellerSetupRoute,
  AuthenticatedSellingRoute: AuthenticatedSellingRoute,
  AuthenticatedShopperRoute: AuthenticatedShopperRoute,
  AuthenticatedShopperPayoutsRoute: AuthenticatedShopperPayoutsRoute,
  AuthenticatedSuggestRoute: AuthenticatedSuggestRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedListingsListingIdEditRoute:
    AuthenticatedListingsListingIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  GlossaryRoute: GlossaryRoute,
  PoliciesRoute: PoliciesRoute,
  SellRoute: SellRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  SellersSlugRoute: SellersSlugRoute,
  ShoppersSlugRoute: ShoppersSlugRoute,
  ApiInternalReviewEmailsRoute: ApiInternalReviewEmailsRoute,
  ApiInternalSavedSearchesRoute: ApiInternalSavedSearchesRoute,
  ApiPublicCatalogMediaSplatRoute: ApiPublicCatalogMediaSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
