-- Compatibility marker for the original open seller-review migration.
--
-- The seller_reviews table, policies, and RPCs are created by
-- 20260919211826_fa39e342-7318-4d93-9679-866e738283c8.sql. This migration
-- used to recreate those objects and caused a fresh/replayed migration run
-- to fail with "relation seller_reviews already exists". Keep this file in
-- the migration history without duplicating the objects.
