// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udxxfuticbxwiehoepeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkeHhmdXRpY2J4d2llaG9lcGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2NTcxNDMsImV4cCI6MjEwNTIzMzE0M30.YEj-okbKL_USQ1LV4i0nfgBs1yubTFMBuwo20qW6Ii0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});